### PR TITLE
Doc 67

### PR DESCRIPTION
**Pull request by attiks**
Index title for documents as lowercase label so wildcard will work.

Might be a good idea to add a silk test.

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
Seems to have affected the filter - from the test failure, first one passes, second doesn't:

```
GET http://docstore-travis-site/api/v1/documents/test-document-crud

  Accept: "application/json"

  API-KEY: "abcd"



{"_count":1,"_start":0,"results":[{"uuid":"e3a086f1-a3b3-4f93-b773-9c79ecfabe71","revision_id":1,"langcode":"en","published":true,"created":"2021-07-26T10:18:39+00:00","changed":"2021-07-26T10:18:39+00:00","author":"hid_123456789","silk_my_id":42,"type":"test_doc_crud","type_uuid":"79e0935d-55e9-4a54-9d5a-49a660cdaad4","title":"Minimal","provider_uuid":"3fa30ed9-b3fc-431a-a60b-41689bba31a3"}]}



GET http://docstore-travis-site/api/v1/documents/test-document-crud

  Accept: "application/json"

  API-KEY: "abcd"

  filter[title]: "Minimal"



{"_count":0,"_start":0,"results":[]}



Data.results[0].uuid expected string: "e3a086f1-a3b3-4f93-b773-9c79ecfabe71"  actual: (missing)  

--- FAIL: GET /documents/{doc_type_endpoint} 

 silk_document_crud.md:378 - Data.results[0].uuid doesn't match  
```

**Comment by attiks** [comment]
@lazysoundsystem I'll have a look

**Comment by attiks** [comment]
Fixed, back to you @lazysoundsystem

**Review by lazysoundsystem — APPROVED** [review]
Thanks, looking good - and plus one for automated tests, I don't think I'd have caught that.

**Comment by attiks** [comment]
> I don't think I'd have caught that.

Same here ;-)

**Pull request merged**
