### PR TITLE
AR-248: Remove duplicate themes

### PR DESCRIPTION
**Pull request by attiks**

### CODE REVIEW

**Review by lazysoundsystem — APPROVED** [review]
Tested and it works well for HRinfo Themes.

Note that there are also Themes from the RW vocabulary in the same DS vocabulary. I don't know if this is going to cause problems, or inconsistent tagging.

e.g we now have HIV/AIDS and HIV/Aids, and "Disaster Management" and "Disaster management" - do we want to remove the RW vocabulary for now, and add it back separately?

**Comment by attiks** [comment]
> e.g we now have HIV/AIDS and HIV/Aids, and "Disaster Management" and "Disaster management" - do we want to remove the RW vocabulary for now, and add it back separately?

Code updated to ignore case

**Comment by lazysoundsystem** [comment]
We might need a ticket to work out what we want to happen here. There are others that are very similar: "Safety and Security" "Safety & Security", and others that are less similar "Climate Change and Environment" "Climate" - but the question is whether we want to merge the HRinfo and RW theme vocabularies into one, or deal with them separately. I'm not sure what the answer is.

**Comment by emmajane** [comment]
I mentioned to @lazysoundsystem on our call today that https://vocabulary.unocha.org/ lists the "official" source for Themes as the ReliefWeb API. Let's put together a backlog ticket to have a more direct integration and leave things a bit messy for now. At some point in the future we'll need to do a migration to get all themes onto the RW themes but in the meantime it doesn't prevent editors from putting in *something*. 

cc @andrejverity

**Comment by lazysoundsystem** [comment]
See also: https://humanitarian.atlassian.net/browse/AR-264

**Pull request merged**
